# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
depedencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    version: 0.8.10
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
networks:
  default: development
  mainnet-fork:
    cmd_settings:
      unlock: 
        - 0x748dE14197922c4Ae258c7939C7739f3ff1db573 #Dai Holder
        - 0xcdE35b62c27d70b279cf7d0AA1212fFA9e938CEf #Ether Holder
console:
  show_colors: true
  color_style: monokai
  auto_suggest: true
  completions: true
  editing_mode: emacs
dotenv: .env
wallets:
  from_mnemonic: ${MNEMONIC}