# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
depedencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    version: 0.8.1
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
networks:
  default: development
  mainnet-fork:
    dai: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
    usdt: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
    LendingPoolAddressProvider: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
    LendingPoolAddress: "0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9"
    cmd_settings:
      unlock:
        - 0x000000000000000000000000000000000000dEaD #burn address
console:
  show_colors: true
  color_style: monokai
  auto_suggest: true
  completions: true
  editing_mode: emacs
dotenv: .env
wallets:
  from_mnemonic: ${MNEMONIC}